### ISSUE TITLE
TypeError: Cannot read property 'write' of undefined

### ISSUE THREAD

**Issue by Discreater** [drom/action-verilator#1]
Here is my yaml jobs:
```yaml
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Set up Verilator
      uses: drom/action-verilator@v0.1.11
    - name: Run tests
      run: |
        cd chisel
        sbt 'testOnly soc.AutoTest'
```

Here is the complete error message：
```
Run drom/action-verilator@v0.1.11
  with:
    version: 4.020
  env:
    JAVA_HOME: /opt/hostedtoolcache/jdk/8.0.252/x64
    JAVA_HOME_8.0.252_x64: /opt/hostedtoolcache/jdk/8.0.252/x64
action-verilator:started
action-verilator: 
/home/runner/work/_actions/drom/action-verilator/v0.1.11/dist/action.js:18
    process.stdout.write(cmd.toString() + os.EOL);
                   ^

TypeError: Cannot read property 'write' of undefined
    at Object.issueCommand (/home/runner/work/_actions/drom/action-verilator/v0.1.11/dist/action.js:18:20)
    at Object.setOutput (/home/runner/work/_actions/drom/action-verilator/v0.1.11/dist/action.js:152:15)
    at Object.6.@actions/core (/home/runner/work/_actions/drom/action-verilator/v0.1.11/dist/action.js:834:6)
    at o (/home/runner/work/_actions/drom/action-verilator/v0.1.11/dist/action.js:1:265)
    at r (/home/runner/work/_actions/drom/action-verilator/v0.1.11/dist/action.js:1:431)
    at Object.<anonymous> (/home/runner/work/_actions/drom/action-verilator/v0.1.11/dist/action.js:1:460)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
```
